# Generated by Django 3.2.12 on 2022-02-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callForMoviesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='author',
            new_name='director',
        ),
    ]
