# Generated by Django 3.2.12 on 2022-03-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callForMoviesApp', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='record',
            field=models.FileField(default='default', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
