# Generated by Django 3.2.12 on 2022-03-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callForMoviesApp', '0005_auto_20220301_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text_french',
            field=models.TextField(blank=True, default='not translated', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_german',
            field=models.TextField(blank=True, default='not translated', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_spanish',
            field=models.TextField(blank=True, default='not translated', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, default='not converted', null=True),
        ),
    ]
